import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import masterRouter from "./master";
import activityLogsRouter from "./activity-logs";
import kpiRouter from "./kpi";
import tasksRouter from "./tasks";
import complaintsRouter from "./complaints";
import announcementsRouter from "./announcements";
import messagesRouter from "./messages";
import chatsRouter from "./chats";
import handoverRouter from "./handover";
import notificationsRouter from "./notifications";
import systemRouter from "./system";
import pushRouter from "./push";
import wallboardRouter from "./wallboard";
import branchesAnalyticsRouter from "./branches-analytics";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(branchesAnalyticsRouter);
router.use(masterRouter);
router.use(activityLogsRouter);
router.use(kpiRouter);
router.use(tasksRouter);
router.use(complaintsRouter);
router.use(announcementsRouter);
router.use(messagesRouter);
router.use(chatsRouter);
router.use(handoverRouter);
router.use(notificationsRouter);
router.use(systemRouter);
router.use(pushRouter);
router.use(wallboardRouter);

export default router;
